       ORG         57
       SPL.A  #     1, $     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, $     1     
       SPL.BA #     1, $     1     
       SPL.F  #     1, $     1     
       SPL.X  #     1, $     1     
       SPL.I  #     1, $     1     
       SPL.I  $     1, $     1     
       SPL.A  #     1, $     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, $     1     
       SPL.BA #     1, $     1     
       SPL.F  #     1, $     1     
       SPL.X  #     1, $     1     
       SPL.I  #     1, $     1     
       SPL.I  $     1, $     1     
       SPL.A  #     1, $     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, $     1     
       SPL.BA #     1, $     1     
       SPL.F  #     1, $     1     
       SPL.X  #     1, $     1     
       SPL.I  #     1, $     1     
       SPL.I  $     1, $     1     
       SPL.A  #     1, $     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, $     1     
       SPL.BA #     1, $     1     
       SPL.F  #     1, $     1     
       SPL.X  #     1, $     1     
       SPL.I  #     1, $     1     
       SPL.I  $     1, $     1     
       SPL.A  #     1, $     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, $     1     
       SPL.BA #     1, $     1     
       SPL.F  #     1, $     1     
       SPL.X  #     1, $     1     
       SPL.I  #     1, $     1     
       SPL.I  $     1, $     1     
       SPL.A  #     1, $     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, $     1     
       SPL.BA #     1, $     1     
       SPL.F  #     1, $     1     
       SPL.X  #     1, $     1     
       SPL.I  #     1, $     1     
       SPL.I  $     1, $     1     
       SPL.A  #     1, $     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, $     1     
       MOV.I  >     9, }     9     
       MOV.I  >     8, }     8     
       MOV.I  >     7, }     7     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  >    11, }    11     
       MOV.I  >    10, }    10     
       MOV.I  >     9, }     9     
       MOV.I  >     8, }     8     
       MOV.I  >     7, }     7     
       MOV.I  >     6, }     6     
       MOV.I  >     5, }     5     
       MOV.I  >     4, }     4     
       MOV.I  >     3, }     3     
       MOV.I  >     2, }     2     
       MOV.I  >     1, }     1     
       SPL.B  $  1431, $     8     
       MOV.I  >    -1, }    -1     
       MOV.I  >    -2, }    -2     
       MOV.I  >    -3, }    -3     
       MOV.I  >    -4, }    -4     
       MOV.I  >    -5, }    -5     
       DAT.F  }    -6, }    -6     
       MOV.I  >     1, }     1     
       SUB.F  *     9, @     3     
       SNE.I  $    -9, $    -1     
       SUB.F  *     7, $    -1     
       SEQ.I  *    -2, @    -2     
       SLT.AB #    27, @    -1     
       DJN.F  $    -5, <  -349     
       MOV.B  @    -3, #     0     
       MOV.AB #     8, $     3     
       MOV.I  $     4, <    -2     
       MOV.I  $     3, <    -3     
       DJN.B  $    -2, #     0     
       JMZ.A  $   -11, $   -12     
       SPL.B  # -3147, $ -3147     
       MOV.I  $     2, >    -4     
       DJN.F  $    -1, {    -5     
       DAT.F  $     3, $    10     
       MOV.I  $     4, <    -2     
       MOV.I  $     3, <    -3     
       DJN.B  $    -2, #     0     
       JMZ.A  $   -11, $   -12     
       SPL.B  # -3147, $ -3147     
       MOV.I  $     2, >    -4     
       DJN.F  $    -1, {    -5     
       DAT.F  $     3, $    10     
       END
